### ISSUE TITLE
NaNs in mosaik .pkl files

### ISSUE THREAD

**Issue by hopkinslaurel** [Global-Policy-Lab/mosaiks-paper#7]
Hi there! I'm attempting to rerun some of the analysis, starting with 1_run_regressions.ipynb. However, I get an error (stemming from line 106 in solve_functions.py) that the input contains NaNs. This happens for both CONTUS_UAR.pkl and CONTUS_POP.pkl. I looked into both CONTUS files and it appears that over half of the rows are NaNs. 

For reference, I cloned the github repo, downloaded the data from Code Ocean Capsule, and created a virtual environment with environment .yml.

**Comment by bolliger32** [comment]
Hi @hopkinslaurel . I just double-checked the `CONTUS_UAR.pkl` file and it does not have any nans. I would imagine the same is true of `CONTUS_POP.pkl`. A couple of things come to mind that may be going on.

1. You might be loading the file in a manner that introduces NaN's somehow? The way I would suggest loading it (which you may have already done): `np.load("CONTUS_UAR.pkl", allow_pickle=True)`
2. You might be using an old version of the code ocean capsule and/or the repo? This link should take you to the latest version (v2) that was published alongside our manuscript: https://codeocean.com/capsule/6456296. I think even in v1 these files did not contain NaN's...but I can't confirm for sure without going back and digging a bit more.

As an aside, I would recommend using the code ocean capsule for computing, rather than just a data archive, if you run into more issues like this. The workflow has been confirmed to replicate exactly on the capsule, so using the computational tools provided by the platform would be helpful in debugging. The author team unfortunately has minimal time available for troubleshooting. We're certainly happy to help when needed, but I think CO is a great place to start. I notice that they have started to require a request in order to use GPU machines (which our capsule requires) but I imagine they would grant that request quickly if you inform them that you're looking to troubleshoot reproducing an existing capsule.

**Comment by hopkinslaurel** [comment]
Hi @bolliger32, thanks for the quick reply! 

I too directly loaded CONTUS_UAR.pkl and CONTUS_POP.pkl and didn't see any NaN's. After a healthy amount of debugging, I realized the NaN's were being introduced by the merge() function in data_parser.py. I'm not sure as to why NaN's were being introduced, but I was able to create a workaround. Thanks for the help!

**Comment by bolliger32** [comment]
Great! Glad you got it working
